name: 'Create .env file'
description: 'This GitHub Action helps to create a .env file'
author: 'Alexey Savelyev'
inputs:
    name:
        description: 'The filename for the envfile'
        required: false
        default: '.env'
    directory:
        description: 'The directory to put the envfile in'
        required: false
        default: ''
    fail_on_empty:
        description: 'Fail if an env key is an empty string'
        required: false
        default: 'false'
    sort_keys:
        description: 'Sort the keys alphabetically'
        required: false
        default: 'false'

runs:
    using: 'node20'
    main: 'dist/index.js'