name: 'Create .env file'
description: 'This GitHub Action helps to replace all placeholders like ${{name}} in file'
author: 'Alexey Savelyev with AI'
inputs:
    template_path:
        description: 'Path to the template file'
        required: true
    data_path:
        description: 'Path to the JSON data file'
        required: true
    output_path:
        description: 'Path to save the output file'
        required: false
        default: 'output.txt'

runs:
    using: 'node20'
    main: 'dist/index.js'